import { NextRequest, NextResponse } from "next/server";

function fallback(messages:{role:string;content:string}[]){
  const answers=messages.filter(m=>m.role==="user").map(m=>m.content);const joined=answers.join(" ");const words=joined.trim().split(/\s+/).length;const avg=words/Math.max(answers.length,1);
  const relevant=/react|angular|node|python|java|php|laravel|api|database|sql|typescript|framework|cloud|git/i.test(joined);
  const evidence=/built|created|implemented|solved|improved|designed|developed|optimized/i.test(joined);
  const scores={communication:Math.min(10,5+Math.round(avg/14)),confidence:Math.min(10,6+(answers.filter(a=>a.length>90).length>2?2:1)),technical:Math.min(10,5+(relevant?2:0)+(avg>25?1:0)),problemSolving:Math.min(10,5+(evidence?2:0)+(avg>30?1:0)),project:Math.min(10,5+(evidence?2:0)+(joined.length>600?1:0))};
  const overall=Number((Object.values(scores).reduce((a,b)=>a+b,0)/5).toFixed(1));
  return {scores,overall,summary:`The candidate completed every screening stage and achieved ${overall}/10. The responses indicate ${scores.technical>=8?"strong":"developing"} technical depth, ${scores.communication>=8?"clear and structured":"generally clear"} communication, and ${evidence?"evidence of practical project ownership":"a need for deeper practical validation"}.`,strengths:[relevant?"Relevant technical foundation":"Positive learning attitude",evidence?"Practical project exposure":"Completed the full screening","Clear career intent"],concerns:[avg<20?"Several responses need more detail":"Validate claims in a live technical round",!evidence?"Limited measurable project outcomes":"Explore system design depth"],recommendation:overall>=8?"Strongly recommend next round":overall>=6.5?"Proceed to technical round":"Hold for recruiter review",aiMode:"demo"};
}

export async function POST(req:NextRequest){const body=await req.json();const key=process.env.OPENAI_API_KEY;if(!key)return NextResponse.json(fallback(body.messages||[]));try{const res=await fetch("https://api.openai.com/v1/chat/completions",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${key}`},body:JSON.stringify({model:process.env.OPENAI_MODEL||"gpt-4o-mini",temperature:.2,response_format:{type:"json_object"},messages:[{role:"system",content:"You are a fair technical recruiter. Evaluate the transcript. Return JSON only with scores (communication, confidence, technical, problemSolving, project: integers 1-10), overall number, summary string, strengths string array, concerns string array, recommendation string. Use evidence only; never infer protected traits."},{role:"user",content:JSON.stringify(body.messages||[])}]})});if(!res.ok)throw new Error();const data=await res.json();return NextResponse.json({...JSON.parse(data.choices[0].message.content),aiMode:"ai"});}catch{return NextResponse.json({...fallback(body.messages||[]),aiMode:"fallback"});}}
